services:
  postgres-node1:
    build:
      context: .
      dockerfile: ./shared/Dockerfile
    container_name: postgres-node1
    environment:
      - SERVER_NAME=postgres-node1.local
      - NODE_ID=1
    ports:
      - "5432:5432"
      - "2201:22"
    cap_add:
      - SYS_CHROOT
      - AUDIT_WRITE
      - CAP_NET_RAW
    shm_size: 256m
    volumes:
      - ./node1/certs:/tmp/certs
      - ./client-certs:/tmp/client-certs
      - ./ca:/tmp/ca:ro

  postgres-node2:
    build:
      context: .
      dockerfile: ./shared/Dockerfile
    container_name: postgres-node2
    environment:
      - SERVER_NAME=postgres-node2.local
      - NODE_ID=2
    ports:
      - "5433:5432"
      - "2202:22"
    cap_add:
      - SYS_CHROOT
      - AUDIT_WRITE
      - CAP_NET_RAW
    shm_size: 256m
    volumes:
      - ./node2/certs:/tmp/certs
      - ./client-certs:/tmp/client-certs
      - ./ca:/tmp/ca:ro

  postgres-node3:
    build:
      context: .
      dockerfile: ./shared/Dockerfile
    container_name: postgres-node3
    environment:
      - SERVER_NAME=postgres-node3.local
      - NODE_ID=3
    ports:
      - "5434:5432"
      - "2203:22"
    cap_add:
      - SYS_CHROOT
      - AUDIT_WRITE
      - CAP_NET_RAW
    shm_size: 256m
    volumes:
      - ./node3/certs:/tmp/certs
      - ./client-certs:/tmp/client-certs
      - ./ca:/tmp/ca:ro
